### ISSUE TITLE
Currently not possible to switch to a different user

### ISSUE THREAD

**Issue by wakonig** [paulscherrerinstitute/scilog#134] opened 2022-12-08 13:00 UTC
It seems as if the login through keycloak is remembered, which prohibits users to change accounts.

**Comment by minottic** [comment] 2023-02-14 15:04
duplicate of #168 . Should I close it @wakonig ?

**Comment by minottic** [comment] 2023-02-16 14:17
closed by https://github.com/paulscherrerinstitute/scilog-ci/pull/66

**Closed by minottic** 2023-02-16 14:17 UTC
Labels: bug, priority
