### ISSUE TITLE
Some snippets are not visible after creation. 

### ISSUE THREAD

**Issue by sorokinpsi** [paulscherrerinstitute/scilog#193] opened 2023-02-16 10:11 UTC
![image](https://user-images.githubusercontent.com/125555140/219333667-29bfa738-3735-46a9-bc26-1fb6783d7b85.png)

As can be seen on the image above, the snippets 19 and 22 are not visible. There used to be some text, which I can't extract anymore. This happened in several hours after making them. I've lost 6 entries out of 87 is this way, mostly at the begging of the beamtime. It maybe related to the fact that I tried to edit the logbook on two separate computers under the same PSI account (which would be a very convenient functionality to have).

**Comment by stephan271** [comment] 2023-02-16 10:57
Thanks for giving feedback! Can you send us the URL of your logbook so we can check the contents of the underlying database ?

**Comment by sorokinpsi** [comment] 2023-02-16 10:59
https://scilog.psi.ch/logbooks/63d55df141019825a5a7e315/dashboard

**Comment by sorokinpsi** [comment] 2023-02-16 14:05
The "invisible" snippets are shown correctly in the pdf export of the logbook.

**Comment by stephan271** [comment] 2023-02-16 14:19
Thats already good news :-) . Did not yet have time to look into it more closely, sorry.

**Comment by stephan271** [comment] 2023-02-17 15:42
It seems that some snippet entries were edited quite often. Can you confirm this ? If yes, were the changes always done via the GUI or was sometimes a command line tool involved in editing the data ?

**Comment by sorokinpsi** [comment] 2023-02-17 15:47
There were no command line tools involved. I did edited few snippets several times (like 1-3 times), but no more than that.

**Comment by stephan271** [comment] 2023-02-17 15:58
Ok, thanks.

**Comment by stephan271** [comment] 2023-02-21 11:07
We found some potential bugs related to the way file attachments are handled, especially when file attachments are **deleted**. Can you confirm, if such action happened, i.e. creation of attachments which were subsequently deleted ?

**Comment by sorokinpsi** [comment] 2023-02-21 13:27
We saw that attached pictures disappeared after editing a snippet. And yes, I may have deleted few inserted images, but I never attached any files to that logbook.

**Comment by stephan271** [comment] 2023-03-01 08:40
We have fixed #129 , which we think might be the cause of the issues reported here. Your problem would be follow-up problem of the initial image diting problem. So we will close this issue for now, since the bugfixes have been deployed to the prod system. However if you encounter the problem again please reopen the issue. Thanks for your feedback in any case !

**Closed by stephan271** 2023-03-01 08:40 UTC
Labels: bug, priority
