### ISSUE TITLE
Cannot add new logbook without Location

### ISSUE THREAD

**Issue by htlemke** [paulscherrerinstitute/scilog#52] opened 2022-08-16 18:21 UTC
On the new instance on https://scilog.qa.psi.ch adding a new logbook fails for me. It seems to fail from inability to define a "Location" in the pulldown field (where for me as lemke_h nothing is selectable). This used to work on scilog-test.psi.ch .
Guess location relates to a selection of instruments/beamlines? DEpending on usability, I see the cahnce that someone would ask to use the scilog independent of a particular beamline or combining beamlines, so it could be an optional field for well defined beamlines, otherwise a free floating log.

**Comment by stephan271** [comment] 2022-08-17 10:00
Yes, I can confirm the problem, thanks for pointing out. We will have  alook.
The point you mention about the location definition is already discussed in https://github.com/paulscherrerinstitute/scilog/issues/18 and should be fixed in future in the way you indicate

**Comment by stephan271** [comment] 2022-08-18 14:20
The reason for the problem were historic basesnippet data in the database from a release of scilog before the customer-> any-authenticated-user modification. The fix was to delete the scilog databases for dev and qa and reload the proposal data with the new API server version.

**Closed by stephan271** 2022-08-18 14:20 UTC
Labels: bug, before release
